import { NextPage } from "next";
import Head from "next/head";
import TopAppBar from "../components/TopAppBar";

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Siddhesh Kothadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainContainer">
          <TopAppBar />
        </div>
      </main>
    </div>
  );
};

export default Contact;