import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useTheme } from "next-themes";
import Button from "../components/Button";
import { Text, TextColor, TextSize } from "../components/Text";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSun, faMoon, IconDefinition } from '@fortawesome/free-solid-svg-icons'
import TopAppBar from "../components/TopAppBar";
import ThemeToggleButton from "../components/ThemeToggleButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Siddhesh Kothadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.mainContainer}>
          <TopAppBar />
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
          <div className={styles.banner}>
            <Text size={TextSize.DISPLAY1} color={TextColor.BLACK}>Dynamic Color</Text>
          </div>
        </div>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
